### ISSUE TITLE
Cannot get result from alfred 4

### ISSUE THREAD

**Issue by Wangjunyu** [orf/alfred-quip-workflow#3]
I installed the latest workflow and quip app in my OSX, then set-quip-key ,everything is ok.

But after that, when I search, it always says "No documents found"

**Comment by jerryk2** [comment]
got the same issue "No documents found" on Alfred4. Will support Alfred4 in the further?

**Comment by orf** [comment]
Sorry guys, I don't use Quip anymore, so I cannot maintain this workflow.
